### ISSUE TITLE
application/osgearth_featureeditor doesn't compile with OSG 2.8.5

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#14]
Hi 

I tried to compile osgearth HEAD with OSG 2.8.5 with VS2005. I've the following errors:

osgearth_featureeditor.cpp
.\osgearth_featureeditor.cpp(65) : error C2039: 'DraggerCallback' : is not a member of 'osgManipulator'
.\osgearth_featureeditor.cpp(65) : error C2504: 'DraggerCallback' : base class undefined
.\osgearth_featureeditor.cpp(143) : warning C4018: '<' : signed/unsigned mismatch
.\osgearth_featureeditor.cpp(154) : error C2039: 'setHandleEvents' : is not a member of 'osgEarth::Util::IntersectingDragger'
        \src\osgEarthUtil/Draggers(47) : see declaration of 'osgEarth::Util::IntersectingDragger'
.\osgearth_featureeditor.cpp(155) : error C2039: 'addDraggerCallback' : is not a member of 'osgEarth::Util::IntersectingDragger'
        \src\osgEarthUtil/Draggers(47) : see declaration of 'osgEarth::Util::IntersectingDragger'
.\osgearth_featureeditor.cpp(434) : warning C4018: '<' : signed/unsigned mismatch

Cheers,
Remo
