### ISSUE TITLE
master doesn't build with OSG 3.2.3

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#700]
\osgEarthAnnotation\PlaceNode.cpp(206): error C2039: 'getBoundingBox' : is not a member of 'osg::Geometry'

getBoundingBox -> getBound

**Comment by gwaldron** [comment]
fixed. thanks.

**Comment by remoe** [comment]
The current master also not build with 3.2.3:

```
src\osgEarthAnnotation\LabelNode.cpp(192): error C2039: 'getBoundingBox' : is not a member of 'osg::Drawable'
src\osgEarthAnnotation\PlaceNode.cpp(264): error C2039: 'getBoundingBox' : is not a member of 'osg::Drawable'
```

**Comment by gwaldron** [comment]
fixed, thx
