### ISSUE TITLE
Failure to build with external tinyxml

### ISSUE THREAD

**Issue by landryb** [gwaldron/osgearth#1002]
During build, when one of the osgearth binaries is linked with osgearth, linking fails:

```
/usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0: undefined reference to `osgEarth::TiXmlElement::TiXmlElement(char const*)'
/usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0: undefined reference to `osgEarth::TiXmlDocument::TiXmlDocument()'
/usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0: undefined reference to `osgEarth::TiXmlDocument::Accept(osgEarth::TiXmlVisitor*) const'
/usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0: undefined reference to `osgEarth::TiXmlDeclaration::TiXmlDeclaration(char const*, char const*, char const*)'
/usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0: undefined reference to `osgEarth::TiXmlNode::FirstChildElement() const'
/usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0: undefined reference to `osgEarth::TiXmlElement::SetAttribute(char const*, char const*)'
/usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0: undefined reference to `vtable for osgEarth::TiXmlText'
/usr/local/lib/libOpenThreads.so.1.0: undefined reference to `_thread_cleanup_pop'
/usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0: undefined reference to `osgEarth::TiXmlNode::TiXmlNode(osgEarth::TiXmlNode::NodeType)'
/usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0: undefined reference to `osgEarth::TiXmlNode::~TiXmlNode()'
/usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0: undefined reference to `osgEarth::TiXmlDocument::Parse(char const*, TiXmlParsingData*, TiXmlEncoding)'
/usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0: undefined reference to `vtable for osgEarth::TiXmlDocument'
/usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0: undefined reference to `osgEarth::TiXmlNode::LinkEndChild(osgEarth::TiXmlNode*)'
/usr/local/lib/libOpenThreads.so.1.0: undefined reference to `_thread_cleanup_push'
/usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0: undefined reference to `osgEarth::TiXmlAttribute::Next() const'
```

Probably caused by PR #988 ..

on a unrelated note, osgearth from master builds and runs fine on OpenBSD, using QGIS globe plugin. Nice work ! Expecting a 2.9 release :)

**Comment by gwaldron** [comment]
I have not seen this error nor can I reproduce it. Any discoveries for your particular platform are appreciated.

**Comment by landryb** [comment]
Well, this is on OpenBSD, with cmake 3.9.3 and passing `-DWITH_EXTERNAL_TINYXML=TRUE` to it - building against openscenegraph 3.4.1 itself built against qt5. I'll retry a clean build, but building against the bundled/internal tinyxml works, that's just awkward.. and i managed to build osgearth 2.8 fine against a systemwide tinyxml.

**Comment by landryb** [comment]
The TiXmlElement constructor exists in the systemwide tinyxml, albeit just not in the osgEarth namespace, hence me thinking it was related to pr #988 
```
$nm -g /usr/local/lib/libtinyxml.so.0.0 |grep TiXmlElement|c++filt|grep :TiXmlElement
00002440 T TiXmlElement::TiXmlElement(char const*)
00002560 T TiXmlElement::TiXmlElement(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
00002680 T TiXmlElement::TiXmlElement(TiXmlElement const&)
```

**Comment by landryb** [comment]
And when built against systemwide tinyxml, libosgEarth.so has almost no TiXmlElement references:
```
$nm -g /usr/obj/ports/osgearth-2.9pre0/build-amd64/lib/libosgEarth.so.0.0|grep TiXmlElement|c++filt
         U osgEarth::TiXmlElement::SetAttribute(char const*, char const*)
         U osgEarth::TiXmlElement::TiXmlElement(char const*)
```

**Comment by gwaldron** [comment]
Ah; I forgot the ability to externalize tinyxml even existed. I will take a look

**Comment by landryb** [comment]
And of course it builds with with external tinyxml if i locally revert pr #988 so that's definitely related :)

**Comment by gwaldron** [comment]
Do you want to take a shot at fixing this? If not, we may punt on it for 2.9.

**Comment by landryb** [comment]
sorry but c++ namespaces is all voodoo to me. It's just sad that #988 broke this possibility..

**Comment by jasonbeverage** [comment]
Why do we need to link against external tinyxml in the first place?  There was some distro that wasn't happy about just including it as a header only file for some reason IIRC.  rapidxml is used in the KML driver as header only and no one has complained, can we just switch over completely to using rapidxml as header only and drop tinyxml completely?

**Comment by gwaldron** [comment]
Closing due to inactivity

**Comment by JackBoosY** [comment]
Same issue, when building tinyxml first and building osgearth last using vcpkg.

**Comment by JackBoosY** [comment]
The reason why this issue happend is because here:
https://github.com/gwaldron/osgearth/blob/f17660028ed850a9325c94855af2060631430209/src/osgEarth/XmlUtils.cpp#L22

Because `xmlutils.cpp` and the internal `tinyxml.h` are at the same level of directory, no matter whether the internal tinyxml is used or the external tinyxml is used, osgearth will **always** use the internal tinyxml **symbol declarations**, resulting in the tinyxml symbol being searched for containing osgearth namespace.

I think this design (place tinyxml source code into source) is a bad idea.
