### ISSUE TITLE
osgEarth 2.8 failed to build

### ISSUE THREAD

**Issue by willysr** [gwaldron/osgearth#865]
I tested this on Slackware64-14.2 with following deps installed:
- OpenSceneGraph-3.4.0
- gdal-2.1.3
- geos-3.6.1
- proj-4.9.3

Error message:
```
In file included from /tmp/SBo/osgearth-2.8/src/osgEarthSymbology/GEOS.cpp:25:0:
/usr/include/geos/geom/GeometryFactory.h: In constructor ‘osgEarth::Symbology::GEOSContext::GEOSContext()’:
/usr/include/geos/geom/GeometryFactory.h:453:2: error: ‘geos::geom::GeometryFactory::GeometryFactory(const geos::geom::PrecisionModel*)’ is protected
  GeometryFactory(const PrecisionModel *pm);
  ^
/tmp/SBo/osgearth-2.8/src/osgEarthSymbology/GEOS.cpp:219:52: error: within this context
     _factory = new geos::geom::GeometryFactory( pm );
                                                    ^
In file included from /tmp/SBo/osgearth-2.8/src/osgEarthSymbology/GEOS.cpp:25:0:
/usr/include/geos/geom/GeometryFactory.h: In destructor ‘osgEarth::Symbology::GEOSContext::~GEOSContext()’:
/usr/include/geos/geom/GeometryFactory.h:474:10: error: ‘virtual geos::geom::GeometryFactory::~GeometryFactory()’ is protected
  virtual ~GeometryFactory();
          ^
/tmp/SBo/osgearth-2.8/src/osgEarthSymbology/GEOS.cpp:227:12: error: within this context
     delete _factory;
            ^
In file included from /tmp/SBo/osgearth-2.8/src/osgEarthSymbology/GEOS.cpp:25:0:
/usr/include/geos/geom/GeometryFactory.h: In member function ‘void osgEarth::Symbology::GEOSContext::disposeGeometry(geos::geom::Geometry*)’:
/usr/include/geos/geom/GeometryFactory.h:474:10: error: ‘virtual geos::geom::GeometryFactory::~GeometryFactory()’ is protected
  virtual ~GeometryFactory();
          ^
/tmp/SBo/osgearth-2.8/src/osgEarthSymbology/GEOS.cpp:337:20: error: within this context
             delete f;
                    ^
src/osgEarthSymbology/CMakeFiles/osgEarthSymbology.dir/build.make:350: recipe for target 'src/osgEarthSymbology/CMakeFiles/osgEarthSymbology.dir/GEOS.cpp.o' failed
make[2]: *** [src/osgEarthSymbology/CMakeFiles/osgEarthSymbology.dir/GEOS.cpp.o] Error 1
CMakeFiles/Makefile2:333: recipe for target 'src/osgEarthSymbology/CMakeFiles/osgEarthSymbology.dir/all' failed
make[1]: *** [src/osgEarthSymbology/CMakeFiles/osgEarthSymbology.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ferdna** [comment]
i was able to compile osgEarth 2.8 with GEOS 3.5.0

**Comment by gwaldron** [comment]
Thanks. I will open a new ticket for GEOS 3.6 support.

**Comment by filnet** [comment]
I submitted a PR to compile with geos 3.6.1

**Comment by willysr** [comment]
@filnet in which project? i don't see any PR in osgEarth's PR list

**Comment by filnet** [comment]
Here https://github.com/gwaldron/osgearth/pulls
and here https://github.com/gwaldron/osgearth/pull/848
