### ISSUE TITLE
Build issue using cesium-native...

### ISSUE THREAD

**Issue by keince** [gwaldron/osgearth#2864]
I'm trying to build osgEarth 3.7.2 on Windows with support for cesium-native library. I'm following the instructions from https://docs.osgearth.org/en/latest/cesium_native.html#install.html and getting the following errors on the configuration...
```
CMake Warning at cmake/FindCesiumNative.cmake:81 (message):
  Cesium Native: Could NOT find csprng
Call Stack (most recent call first):
  cmake/FindCesiumNative.cmake:107 (find_cesium_library)
  D:/vcpkg/scripts/buildsystems/vcpkg.cmake:904 (_find_package)
  src/osgEarthCesium/CMakeLists.txt:1 (find_package)


CMake Error at C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CesiumNative (missing: CESIUM_NATIVE_FOUND)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCesiumNative.cmake:134 (find_package_handle_standard_args)
  D:/vcpkg/scripts/buildsystems/vcpkg.cmake:904 (_find_package)
  src/osgEarthCesium/CMakeLists.txt:1 (find_package)


-- Configuring incomplete, errors occurred!

D:\osgearth3.7.2\repo>
```

I noticed that there were issues raised with `csprng` a year ago but it wasn't clear if there was a resolution to the problem.

Any input or help would be appreciated...

**Comment by jasonbeverage** [comment]
Are you using the v0.37.0 branch of cesium-native as specified in the docs?

**Comment by keince** [comment]
> Are you using the v0.37.0 branch of cesium-native as specified in the docs?

No. Even though I issued the command as outlined in the doc, it still showed that it was "main" and not "v0.37.0". I had to manually do a switch/checkout to get the proper branch. Once I did that, the configuration when through. 

Now, I'm getting the following errors when I try to build osgEarth...

```
D:\osgearth3.7.2\repo\src\osgEarth\GDAL.cpp(425,1): error C2872: 'GDAL': ambiguous symbol [D:\osgearth3.7.2\build\s
rc\osgEarth\osgEarth.vcxproj]
D:\osgearth3.7.2\build\vcpkg_installed\x64-windows\include\gdal_cpp_functions.h(375,11): message : could be 'GDAL'
(compiling source file D:\osgearth3.7.2\repo\src\osgEarth\GDAL.cpp) [D:\osgearth3.7.2\build\src\osgEarth\osgEarth.v
cxproj]
D:\osgearth3.7.2\repo\src\osgEarth\GDAL.cpp(62,15): message : or       'osgEarth::GDAL' [D:\osgearth3.7.2\build\src
\osgEarth\osgEarth.vcxproj]
D:\osgearth3.7.2\repo\src\osgEarth\GDAL.cpp(425,7): error C2039: 'Driver': is not a member of 'GDAL' [D:\osgearth3.
7.2\build\src\osgEarth\osgEarth.vcxproj]
D:\osgearth3.7.2\build\vcpkg_installed\x64-windows\include\gdal_cpp_functions.h(375,11): message : see declaration
of 'GDAL' [D:\osgearth3.7.2\build\src\osgEarth\osgEarth.vcxproj]
D:\osgearth3.7.2\repo\src\osgEarth\GDAL.cpp(425,7): error C3083: 'Driver': the symbol to the left of a '::' must be
 a type [D:\osgearth3.7.2\build\src\osgEarth\osgEarth.vcxproj]
D:\osgearth3.7.2\repo\src\osgEarth\GDAL.cpp(425,16): error C2523: 'GDAL::~Driver': destructor tag mismatch [D:\osge
arth3.7.2\build\src\osgEarth\osgEarth.vcxproj]
D:\osgearth3.7.2\repo\src\osgEarth\GDAL.cpp(425,16): error C2039: '{dtor}': is not a member of 'GDAL' [D:\osgearth3
.7.2\build\src\osgEarth\osgEarth.vcxproj]
D:\osgearth3.7.2\build\vcpkg_installed\x64-windows\include\gdal_cpp_functions.h(375,11): message : see declaration
of 'GDAL' [D:\osgearth3.7.2\build\src\osgEarth\osgEarth.vcxproj]
D:\osgearth3.7.2\repo\src\osgEarth\GDAL.cpp(426,1): error C4430: missing type specifier - int assumed. Note: C++ do
es not support default-int [D:\osgearth3.7.2\build\src\osgEarth\osgEarth.vcxproj]
D:\osgearth3.7.2\repo\src\osgEarth\GDAL.cpp(427,9): error C2065: '_warpedDS': undeclared identifier [D:\osgearth3.7
.2\build\src\osgEarth\osgEarth.vcxproj]
D:\osgearth3.7.2\repo\src\osgEarth\GDAL.cpp(428,19): error C2065: '_warpedDS': undeclared identifier [D:\osgearth3.
7.2\build\src\osgEarth\osgEarth.vcxproj]
D:\osgearth3.7.2\repo\src\osgEarth\GDAL.cpp(429,14): error C2065: '_srcDS': undeclared identifier [D:\osgearth3.7.2
\build\src\osgEarth\osgEarth.vcxproj]
D:\osgearth3.7.2\repo\src\osgEarth\GDAL.cpp(430,19): error C2065: '_srcDS': undeclared identifier [D:\osgearth3.7.2
\build\src\osgEarth\osgEarth.vcxproj]
```

I checked and the GDAL version it's using in vcpkg is 3.12.0...

**Comment by leadcoder** [comment]
osgEarth need patching to work with GDAL 3.12, see this commit https://github.com/microsoft/vcpkg/commit/8fbf295ab5283313932f65a597a2c1f09a73fafd

**Comment by gwaldron** [comment]
Yes, this is on the todo list, thanks

**Comment by keince** [comment]
So...what version of GDAL should I be using if osgEarth 3.7.2 is not compliant with what vcpkg is using (i.e. 3.12.0)?

**Comment by leadcoder** [comment]
You can use vcpkg pre commit posted above, this was merged last week, Previous GDAL was 3.11 .5 and should work with osgEarth without the patch provided in https://github.com/microsoft/vcpkg/commit/8fbf295ab5283313932f65a597a2c1f09a73fafd

**Comment by gwaldron** [comment]
I pushed an update to compile against GDAL 3.12+, please test.

**Comment by keince** [comment]
> I pushed an update to compile against GDAL 3.12+, please test.

Is this pushed into the `Branch_osgearth-3.7.2` or master?

**Comment by keince** [comment]
I pulled osgEarth master with the change Glenn pushed and many of the errors went away. However, I'm still getting the following errors on the build `cmake --build build --target INSTALL --config RelWithDebInfo`

```
Building Custom Rule D:/osgearth_master/repo/src/applications/osgearth_server/CMakeLists.txt
  osgearth_server.cpp
D:\osgearth_master\repo\src\applications\osgearth_server\osgearth_server.cpp(96,53): error C2039: 'GDAL': is not a
member of 'osgEarth' [D:\osgearth_master\build\src\applications\osgearth_server\osgearth_server.vcxproj]
D:\osgearth_master\repo\src\osgEarth/GDAL(314,1): message : see declaration of 'osgEarth' [D:\osgearth_master\build
\src\applications\osgearth_server\osgearth_server.vcxproj]
D:\osgearth_master\repo\src\applications\osgearth_server\osgearth_server.cpp(96,53): error C3083: 'GDAL': the symbo
l to the left of a '::' must be a type [D:\osgearth_master\build\src\applications\osgearth_server\osgearth_server.v
cxproj]
D:\osgearth_master\repo\src\applications\osgearth_server\osgearth_server.cpp(96,59): error C2039: 'heightFieldToTif
f': is not a member of 'osgEarth' [D:\osgearth_master\build\src\applications\osgearth_server\osgearth_server.vcxpro
j]
D:\osgearth_master\repo\src\osgEarth/GDAL(314,1): message : see declaration of 'osgEarth' [D:\osgearth_master\build
\src\applications\osgearth_server\osgearth_server.vcxproj]
D:\osgearth_master\repo\src\applications\osgearth_server\osgearth_server.cpp(96,59): error C3861: 'heightFieldToTif
f': identifier not found [D:\osgearth_master\build\src\applications\osgearth_server\osgearth_server.vcxproj]
D:\osgearth_master\repo\src\applications\osgearth_server\osgearth_server.cpp(127,45): error C2039: 'GDAL': is not a
 member of 'osgEarth' [D:\osgearth_master\build\src\applications\osgearth_server\osgearth_server.vcxproj]
D:\osgearth_master\repo\src\osgEarth/GDAL(314,1): message : see declaration of 'osgEarth' [D:\osgearth_master\build
\src\applications\osgearth_server\osgearth_server.vcxproj]
D:\osgearth_master\repo\src\applications\osgearth_server\osgearth_server.cpp(127,45): error C3083: 'GDAL': the symb
ol to the left of a '::' must be a type [D:\osgearth_master\build\src\applications\osgearth_server\osgearth_server.
vcxproj]
D:\osgearth_master\repo\src\applications\osgearth_server\osgearth_server.cpp(127,51): error C2039: 'heightFieldToTi
ff': is not a member of 'osgEarth' [D:\osgearth_master\build\src\applications\osgearth_server\osgearth_server.vcxpr
oj]
D:\osgearth_master\repo\src\osgEarth/GDAL(314,1): message : see declaration of 'osgEarth' [D:\osgearth_master\build
\src\applications\osgearth_server\osgearth_server.vcxproj]
D:\osgearth_master\repo\src\applications\osgearth_server\osgearth_server.cpp(127,51): error C3861: 'heightFieldToTi
ff': identifier not found [D:\osgearth_master\build\src\applications\osgearth_server\osgearth_server.vcxproj]
```

**Comment by keince** [comment]
Just pulled the latest change pushed into master. Everything compiles now...

Thank you Glenn and everyone else who chimed in on this...
