### ISSUE TITLE
osgearth_qt_windows not working on 3.0 : OpenGLContext issue

### ISSUE THREAD

**Issue by MCA4213** [gwaldron/osgearth#1329]
I am trying to run the osgearth_qt_windows example on the 3.0 brunch, but I got many errors (same code work on 2.10).

here are the errors:
```
Windows Error #2000: Win32WindowingSystem::OpenGLContext() - Unable to restore current OpenGL rendering context. Reason: The pixel format is invalid.

Unable to create osg::Program "VisibleLayer" contextID=1
VERTEX glCompileShader "RexEngine.SDK.vert.glsl_VERTEX" FAILED
FRAGMENT glCompileShader "RexEngine.SDK.vert.glsl_FRAGMENT" FAILED
VERTEX glCompileShader "oe_rexEngine_vert_model" FAILED
VERTEX glCompileShader "oe_rexEngine_vert_view" FAILED
VERTEX glCompileShader "oe_rex_setTexCoords" FAILED
VERTEX glCompileShader "oe_rexEngine_elevation" FAILED
VERTEX glCompileShader "oe_normalMapVertex" FAILED
FRAGMENT glCompileShader "oe_normalMapFragment" FAILED
VERTEX glCompileShader "oe_rexEngine_morph" FAILED
FRAGMENT glCompileShader "oe_rexEngine_frag" FAILED
VERTEX glCompileShader "oe_VisibleLayer_initOpacity" FAILED
VERTEX glCompileShader "main(vertex)" FAILED
FRAGMENT glCompileShader "main(fragment)" FAILED
Warning: detected OpenGL error 'invalid operation' at after RenderBin::draw(..)
Warning: detected OpenGL error 'invalid operation' at end of SceneView::draw()
glLinkProgram 00000234824F34C0"VisibleLayer" FAILED
Program "VisibleLayer" infolog:
Vertex info
-----------
0(51) : error C3002: call to undefined function "void oe_rexEngine_vert_model(vec4);"
0(52) : error C3002: call to undefined function "void oe_rexEngine_morph(vec4);"
0(53) : error C3002: call to undefined function "void oe_rexEngine_elevation(vec4);"
0(54) : error C3002: call to undefined function "void oe_VisibleLayer_initOpacity(vec4);"
0(57) : error C3002: call to undefined function "void oe_rexEngine_vert_view(vec4);"
0(58) : error C3002: call to undefined function "void oe_rex_setTexCoords(vec4);"
0(59) : error C3002: call to undefined function "void oe_normalMapVertex(vec4);"

Fragment info
-------------
0(58) : error C3002: call to undefined function "void oe_normalMapFragment(vec4);"
0(59) : error C3002: call to undefined function "void oe_rexEngine_frag(vec4);"

Warning: detected OpenGL error 'invalid value' after applying attribute VirtualProgram 00000234EFCAE320

```

If I click on the addView button, the second window is generated correctly.
Any fix for that???
Thanks.

**Comment by gwaldron** [comment]
Which version of OSG are you using?

You might need to call osgEarth::initialize() at the beginning of your app.

**Comment by MCA4213** [comment]
Thanks for the feedback, my osg version is 3.7.0.

The call of **osgEarth::initialize()** has solve the problem, 
thank you.

**Comment by ertanataman** [comment]
Where is "osgEarth::initialize()" ?

**Comment by gwaldron** [comment]
[Here](https://github.com/gwaldron/osgearth/blob/3.0/src/osgEarth/Common#L67).

**Comment by ertanataman** [comment]
Thanks a lot.
I think I could not find since I am using the master branch.

**Comment by ertanataman** [comment]
I had the sfml text rendering problem when a mapnode is read via an earth file. 
"call osgEarth::initialize() at the beginning of your app" also solved it.

**Comment by gwaldron** [comment]
If you're using osgEarth 2.x, you can call this instead:

`osgEarth::Registry::instance()->getCapabilities();`

That is what initialize() does anyway.

**Comment by ertanataman** [comment]
I would if I knew it yesterday:)
Moved to 3.0 and seems ok for now. 
Still good to know if I need to go back. 
Thanks.

**Comment by ertanataman** [comment]
> Which version of OSG are you using?
> 
> You might need to call osgEarth::initialize() at the beginning of your app.

When to call osgEarth::initialize when osgEarth is not linked to main application but linked to a plugin that may (or not) be loaded runtime? 

I tried to call on several things like:
 -in constructor of a class that loads map via osgEarth
 -in a funtion that sets to a static global variable
but it did not help.
