### ISSUE TITLE
osgearth fails to build with Geos 3.6

### ISSUE THREAD

**Issue by Hallot** [gwaldron/osgearth#953]
After upgrading from Geos 3.5.0 to Geos 3.6.2, osgearth fails to build with the following errors:

> osgearth/src/osgEarthSymbology/GEOS.cpp: In constructor 'osgEarth::Symbology::GEOSContext::GEOSContext()':
> osgearth/src/osgEarthSymbology/GEOS.cpp:219:52: error: 'geos::geom::GeometryFactory::GeometryFactory(const geos::geom::PrecisionModel*)' is protected within this context
>      _factory = new geos::geom::GeometryFactory( pm );
>                                                     ^
> In file included from osgearth/src/osgEarthSymbology/GEOS.cpp:25:0:
> /usr/include/geos/geom/GeometryFactory.h:453:2: note: declared protected here
>   GeometryFactory(const PrecisionModel *pm);
>   ^~~~~~~~~~~~~~~
> osgearth/src/osgEarthSymbology/GEOS.cpp: In destructor 'osgEarth::Symbology::GEOSContext::~GEOSContext()':
> osgearth/src/osgEarthSymbology/GEOS.cpp:227:12: error: 'virtual geos::geom::GeometryFactory::~GeometryFactory()' is protected within this context
>      delete _factory;
>             ^~~~~~~~
> In file included from osgearth/src/osgEarthSymbology/GEOS.cpp:25:0:
> /usr/include/geos/geom/GeometryFactory.h:474:10: note: declared protected here
>   virtual ~GeometryFactory();
>           ^
> osgearth/src/osgEarthSymbology/GEOS.cpp: In member function 'void osgEarth::Symbology::GEOSContext::disposeGeometry(geos::geom::Geometry*)':
> osgearth/src/osgEarthSymbology/GEOS.cpp:341:20: error: 'virtual geos::geom::GeometryFactory::~GeometryFactory()' is protected within this context
>              delete f;
>                     ^
> In file included from osgearth/src/osgEarthSymbology/GEOS.cpp:25:0:
> /usr/include/geos/geom/GeometryFactory.h:474:10: note: declared protected here
>   virtual ~GeometryFactory();
>           ^

It looks like the C++ API changed and GeometryFactory became protected.

**Comment by remoe** [comment]
I have successfully build osgEarth master with GEOS 3.6.1

**Comment by Hallot** [comment]
It was using the 2.8 release, so I guess it's been fixed in-between.
Sorry for the spam.
