### ISSUE TITLE
VS2017 15.8: build issue / FeatureSourceIndexNode.cpp

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1187]
can't compile osgEarth with VS2017 15.8:

```
FeatureSourceIndexNode.cpp
vc\tools\msvc\14.15.26726\include\xmemory0(881):error C2440: 'initializing': cannot convert from 'std::pair<const _Kty,_Ty>' to '_Objty'

...
src\osgearthfeatures\featuresourceindexnode.cpp(102): note: see reference to function template instantiation 'void std::_Tree<std::_Tset_traits<_Kty,_Pr,_Alloc,false>>::insert<`anonymous-namespace'::KeyIter<osgEarth::Features::FeatureSourceIndexNode::FIDMap>>(_Iter,_Iter)' being compiled
        with
        [
            _Kty=osgEarth::Features::FeatureID,
            _Pr=std::less<osgEarth::Features::FeatureID>,
            _Alloc=std::allocator<osgEarth::Features::FeatureID>,
            _Iter=`anonymous-namespace'::KeyIter<osgEarth::Features::FeatureSourceIndexNode::FIDMap>
        ]
```

https://github.com/gwaldron/osgearth/blob/master/src/osgEarthFeatures/FeatureSourceIndexNode.cpp#L102

**Comment by remoe** [comment]
osgearth also doesn't compile with VS2017 15.8.1 without this fix.

**Comment by dwickeroth** [comment]
I just tried to compile osgearth version 2.9.0 with VS 15.9.12 and still ran into this error. Cherrypicking the commit from remoe solve the issue.
