### ISSUE TITLE
osgEarth does not build with OSG 3.5.2

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#721]
The latest version of osgEarth with the latest version of OSG build fails. 
There are multiple errors kind of: 

Error C2664	"bool osg::Transform::computeLocalToWorldMatrix(osg::Matrix &,osg::NodeVisitor *) const":cannot convert argument 1 from "osg::Matrixd" to "osg::Matrix &"	osgEarth C:\osgEarth\src\osgEarth\CullingUtils.cpp	191	

Error	C2664	"bool osgEarth::GeoPoint::createWorldToLocal(osg::Matrixd &) const": cannot convert argument 1 from "osg::Matrix" to "osg::Matrixd &"	Plugin osgearth_engine_rex C:\osgEarth\src\osgEarthDrivers\engine_rex\MaskGenerator.cpp	125	

It seems that earlier the mixture of Matrix and Matrixd types was allowed, but not anymore.

**Comment by jasonbeverage** [comment]
Built against the osg master and only had to fix an issue with the TextureBufferSerializer.  Working in c7c1a8c
